version: "3.9"

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    env_file:
      - .env
    command:
      sh -c "python manage.py runserver 0.0.0.0:8000"
    ## add wait_for_db for PostgreSQL
    #command: >
    #  sh -c "python manage.py wait_for_db &&
    #         python manage.py migrate &&
    #         python manage.py runserver 0.0.0.0:8000"
    ### The below is for PostgreSQL