---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Create .env and Test
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: copy envfile
        working-directory: ../../
        run: pwd
      #- name: Create .env
      #  uses: DeveloperRic/action-create-env@v1.0.2
      #  with:
      #    full_text: |
      #      PROD=1
      #      PORT=3000
      #      API_AUDIENCE=api.mydomain.xyz
      #    directory: ${{ github.workspace }}
      #    file_name: .env
      #    fail_on_empty: false
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_SOME_API_KEY: "123456abcdef"
          directory: ../../env-file-test/env-file-test/
          file_name: .env
          fail_on_empty: false
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test"

